### ISSUE TITLE
Error in processing ONT cDNA fastq data

### ISSUE THREAD

**Issue by sunqiangzai** [Bulabula45/Readon#1]
`(base) sutai@sutai-MD72-HB1-00:~/biosoft/Readon$ ./readon -i /home/sutai/data_beifen/TGS_CRC/colon_TGS_normal/ONT_BMK200828-AC195-010001_clean.fq.gz -o /home/sutai/data_beifen/TGS_CRC/colon_TGS_normal/N010001
kmer length: 25
window size: 15 kmers

reads_len: 1610612736
offset: 0
offset_align: 0
reads_cnt: -4117599
terminate called after throwing an instance of 'std::bad_array_new_length'
  what():  std::bad_array_new_length
已中止 (核心已转储)
`

**Comment by sunqiangzai** [comment]
error mode generate the same error

**Comment by sunqiangzai** [comment]
-k 15 -w 24 -s 9， the same parameters also return the same error

**Comment by sunqiangzai** [comment]
also return the same error with SGNex_MCF7_cDNA_replicate1_run3.fastq.gz file

**Comment by sunqiangzai** [comment]
solved after unzip the gz file

**Comment by sunqiangzai** [comment]
what is the meaning of each column

**Comment by siennachen45** [comment]
> what is the meaning of each column

your read id, chromosome, the strand of chr, which strand of your read, upstream gene, downstream gene, hit count of upstream gene, downstream gene

**Comment by sunqiangzai** [comment]
> > what is the meaning of each column
> 
> your read id, chromosome, the strand of chr, which strand of your read, upstream gene, downstream gene, hit count of upstream gene, downstream gene

I got it, thank for your response.
